version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8888:80"
    volumes:
      - ./www:/var/www/html

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pasahitza2023
      MYSQL_DATABASE: users
      MYSQL_USER: juanan
      MYSQL_PASSWORD: pasahitza2023
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

